CREATE DATABASE EQUIPOS_FUTBOL
GO 
USE EQUIPOS_FUTBOL
GO

--CREACION DE TABLAS
CREATE TABLE PERSONAS(
ID INT IDENTITY(1,1),
NOMBRE VARCHAR(500) NOT NULL,
DNI INT NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
CONSTRAINT PK_PERSONAS PRIMARY KEY(ID)
);

CREATE TABLE POSICIONES(
ID INT IDENTITY(1,1),
NOMBRE_POSICION VARCHAR(30),
CONSTRAINT PK_POSICIONES PRIMARY KEY(ID)
);

CREATE TABLE EQUIPOS(
ID INT IDENTITY(1,1),
NOMBRE VARCHAR(30) NOT NULL,
DIRECTOR_TECNICO VARCHAR(30) NOT NULL,
CONSTRAINT PK_EQUIPOS PRIMARY KEY(ID)
);

CREATE TABLE JUGADORES(
ID INT IDENTITY(1,1),
PERSONA INT NOT NULL,
CAMISETA INT NOT NULL,
POSICION INT NOT NULL, 
CONSTRAINT PK_JUGADORES PRIMARY KEY (ID),
CONSTRAINT FK_JUGADORES_PERSONAS FOREIGN KEY (PERSONA) REFERENCES PERSONAS(ID),
CONSTRAINT FK_JUGADORES_POSICION FOREIGN KEY (POSICION) REFERENCES POSICIONES(ID)
);

CREATE TABLE EQUIPOS_JUGADORES(
ID INT IDENTITY(1,1),
EQUIPO INT NOT NULL, 
JUGADOR INT NOT NULL,
CONSTRAINT PK_EQUIPOS_JUGADORES PRIMARY KEY(ID),
CONSTRAINT FK_EQUIPOS_JUGADORES_EQU FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID),
CONSTRAINT FK_EQUIPOS_JUGADORES_JUG FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(ID),
CONSTRAINT UK_EQUIPO_JUGADORES UNIQUE (EQUIPO,JUGADOR)
);
--ALTER


--INSERCIONES DE DATOS
INSERT INTO POSICIONES(NOMBRE_POSICION)
VALUES('Arquero'),('Defensor Izq'),('Defensor Central'),('Defesor Der'),('Mediocampista Izq'),
('Mediocampista Ofensivo'),('Mediocampista Defensivo'),('Mediocampista Der'),
('Delantero Izq'),('Delantero Der'),('Delantero Central')
;

--STORED PROCEDURES
GO
CREATE PROCEDURE SP_INSERTAR_PERSONAS
@nombre varchar(100),
@dni int,
@fecha_nac date
AS
BEGIN
	INSERT INTO PERSONAS(NOMBRE,DNI,FECHA_NACIMIENTO)
	VALUES (@nombre,@dni,@fecha_nac)
END

GO
CREATE PROCEDURE SP_CONSULTAR_PERSONAS
@nombre varchar(100),
@dni int
AS
BEGIN
	SELECT * FROM PERSONAS p WHERE  p.NOMBRE LIKE '%@nombre%' OR p.DNI = @dni
END

GO
CREATE PROCEDURE SP_LISTAR_PERSONAS

AS
BEGIN
	SELECT * FROM PERSONAS 
END

GO
CREATE PROCEDURE SP_LISTAR_POSICIONES
AS
BEGIN
	SELECT * FROM POSICIONES
END

GO
CREATE PROCEDURE SP_INSERTAR_JUGADORES
@persona int,
@camiseta int, 
@posicion int
AS
BEGIN
	INSERT INTO JUGADORES(PERSONA,CAMISETA,POSICION)
	VALUES (@persona,@camiseta,@posicion)
END
GO

CREATE PROCEDURE SP_LISTAR_JUGADORES

AS
BEGIN
	SELECT p.NOMBRE ,j.CAMISETA,po.NOMBRE_POSICION FROM JUGADORES j
	JOIN PERSONAS p ON j.PERSONA = p.ID
	JOIN POSICIONES po ON j.POSICION = po.ID
END

